### ISSUE TITLE
rotate video

### ISSUE THREAD

**Issue by gucasbrg** [digitalmacgyver/vedit#2]
Can I rotate 30/45/69/90 degrees to a video on top of other video? 
thanks

**Comment by digitalmacgyver** [comment]
Hello,

I'm sorry to say my took doesn't have rotational options.

You could use FFMPEG to do 90 and 180 degree rotation of the sources before sending them into vedit.

I'm not aware of any ways to do rotations that aren't 90 degree increments (I'm sure there are some, but I don't know them).
